
trigger:
- master

jobs:
- job: PSLiteDB_Pipeline
  displayName: 'Test, compile and publish PSLiteDB'

pool:
  vmImage: 'ubuntu-latest'

  steps:
  - task: PowerShell@2
    displayName: 'Run tests (individual .ps1 files)'
    inputs:
      targetType: Inline
      script: ./Azure-Pipelines/build.ps1 -Bootstrap -Test


  - task: PublishTestResults@2
    displayName: 'Publish test results'
    inputs:
      testRunner: NUnit
      testResultsFiles: '**/TestResults.xml'
    condition: succeededOrFailed()
